[tools]
bun = "latest"
"github:rojo-rbx/rokit" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:oxfmt" = "latest"
"npm:vscode-langservers-extracted" = "latest"
oxlint = "latest"
tombi = "latest"
